services:
  acme-sh:
    image: nicat23/idracadm7:v5
    container_name: acme.sh
    volumes:
      - ./certs:/certs
      - ./hooks:/hooks
      - ./config:/config
    command: daemon
    stdin_open: true
    tty: true
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true
